# Your personal GitHub token
github_token: 5fee2d1a7796d0d8ed310205c65e6108ec562a07
# Read more: https://github.com/blog/1509-personal-api-tokens
# You can generate it here: https://github.com/settings/tokens

# Guest OS timezone
timezone: Europe/London

# Are we need check box updates for every 'vagrant up'?
box_check_update: false

# Virtual machine name
machine_name: kouosl

# Virtual machine IP
ip: 192.168.83.137

# Virtual machine CPU cores number
cpus: 1

# Virtual machine RAM
memory: 512
